config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  root 'web/home#index'

  post 'auth/:provider', to: 'auth#request', as: :auth_request

  scope module: :web do
    resources :auth, param: :provider, only: [] do
      member do
        get 'callback'
        get 'logout'
      end
    end

    resources :repositories, only: %i[index new create]
    resource :home, only: %i[index]
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  helper_method :current_user

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < Web::ApplicationController
  def callback
    user_info = request.env['omniauth.auth']
    user_nickname = user_info[:info][:nickname]
    user_email = user_info[:info][:email]
    user_token = user_info[:credentials][:token]

    user = User.find_or_initialize_by(email: user_email)
    user.nickname = user_nickname
    user.token = user_token

    flash_message = user.persisted? ? t('auth.welcome_back') : t('auth.login.success')

    if user.save
      flash[:info] = flash_message
      session[:user_id] = user.id
    else
      flash[:alert] = t('auth.login.error')
    end
    redirect_to root_path
  end

  def logout
    reset_session
    redirect_to root_path, notice: t('auth.logout.success')
  end

  def auth_params
    params.require(:user_info)
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < Web::ApplicationController
  def index; end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  require 'octokit'

  before_action :authorize_user

  def index
    @repos = []

    return if current_user.nil?

    @repos = Repository.where(user: current_user)
  end

  def new
    @repos = []
    @repository = Repository.new

    return if current_user.nil?

    client = Octokit::Client.new access_token: current_user.token, auto_paginate: true
    @repos = client.repos.presence || []
  end

  def create
    client = Octokit::Client.new access_token: current_user.token, auto_paginate: true
    selected_repository = client.repository(params[:repository][:github_id].to_i)

    repository = Repository.new
    repository.name = selected_repository[:name]
    repository.github_id = selected_repository[:id]
    repository.full_name = selected_repository[:full_name]
    repository.language = selected_repository[:laguage]
    repository.clone_url = selected_repository[:clone_url]
    repository.ssh_url = selected_repository[:ssh_url]
    repository.user = current_user

    if repository.save
      redirect_to root_path, notice: t('repository.create.success')
    else
      render :new, status: :unprocessable_content
    end
  end

  def authorize_user
    redirect_to root_path, alert: t('auth.not_logged_in') if current_user.nil?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/web/home_helper.rb
# frozen_string_literal: true

module Web::HomeHelper
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web::RepositoriesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || 'Rails Project 66'
    meta name='viewport' content='width=device-width,initial-scale=1'
    meta name='apple-mobile-web-app-capable' content='yes'
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    link rel='manifest' href='/manifest.json'
    link rel='icon' href='/icon.png' type='image/png'
    link rel='icon' href='/icon.svg' type='image/svg+xml'
    link rel='apple-touch-icon' href='/icon.png'
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

  body
    = render 'layouts/shared/nav'
    = render 'layouts/shared/flash'
    #wrapper.d-flex.flex-grow-1
      - if current_user
        = render 'layouts/shared/sidebar'

      .content-wrapper.d-flex.flex-column.flex-grow-1
        main.main-content.flex-glow-1
          = yield

    = render 'layouts/shared/footer'

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
      - if type == 'alert'
        .alert.alert-danger
          = msg
      - else
        .alert.alert-info
          = msg

app/views/layouts/shared/_footer.html.slim
footer.footer.bg-dark.text-white.py-3.text-center
    span = t('.title')

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.stiky-top
    .container-fluid
        = link_to root_path, class: %w[navbar-brand fw-bold] do
            <i class="bi bi-git me-2"></i>
            = t('.title')
        button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
            span.navbar-toggler-icon

        .collapse.navbar-collapse#navbarContent
            span Search here

            ul.navbar-nav.ms-auto.align-items-center
                - if current_user
                    li.nav-item.me-3
                        = link_to root_path, class: %w[nav-link] do
                            i.bi.bi-person-circle.fs-5.me-2
                            = current_user.nickname
                li.nav-item
                    - if current_user
                        = link_to t('.logout_button'), logout_auth_path('github'), class: %w[btn btn-primary]
                    - else
                        = form_tag(auth_request_path('github'), method: 'post', data: { turbo: false }) do
                                button.nav-link type='submit'
                                    i.bi.bi-github.me-2
                                    = t('.login_button')

app/views/layouts/shared/_sidebar.html.slim
aside.sidebar#sidebar
    .sidebar-header.p-3.border-bottom
        h6.text-uppercase.text-muted.mb-0.small Menu
    ul.nav.flex-column.p-2
        li.nav-item
            = link_to repositories_path, class: %w[nav-link active d-flex align-items-center] do
                i.bi.bi-folder.me-3
                = t('repositories.title')

app/views/web/home/index.html.slim
.d-flex.fllex-row.justify-content-center
    .flex-column
        h2 Welcome to RepoAnalyzer
        p RepoAnalyzer is an easy tool to analyze your own github repos

app/views/web/repositories/_form.html.slim
= simple_form_for @repository do |f|
    = f.error_notification
    = f.input :github_id,
        as: :select,
        collection: @repos, label_method: :name, value_method: :id
    = f.button :submit, class: 'btn btn-primary'

app/views/web/repositories/index.html.slim
h2 Repositories list

= link_to t('repositories.new.title'), new_repository_path, class: %w[btn btn-primary]

.table-responsive
    table.table.table-striped.table-sm
        thead
            tr
                th #
                th Name
        tbody
            - @repos.each_with_index do |repo, index|
                tr
                    td = index
                    td = repo.name

app/views/web/repositories/new.html.slim
h1 = t('repository.create.title')

== render 'form', repository: @repository